/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAvatar: typeof import('primevue/avatar')['default']
    PrimeButton: typeof import('primevue/button')['default']
    Primecard: typeof import('primevue/card')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeCarousel: typeof import('primevue/carousel')['default']
    PrimeDivider: typeof import('primevue/divider')['default']
    PrimeFieldset: typeof import('primevue/fieldset')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMenubar: typeof import('primevue/menubar')['default']
    PrimeTab: typeof import('primevue/tab')['default']
    PrimeTabList: typeof import('primevue/tablist')['default']
    PrimeTabPanel: typeof import('primevue/tabpanel')['default']
    PrimeTabPanels: typeof import('primevue/tabpanels')['default']
    PrimeTabs: typeof import('primevue/tabs')['default']
    PrimeTag: typeof import('primevue/tag')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
